## sentence-BERT를 이용한 문장 유사도 측정

In [ ]:
### 필요한 라이브러리 설치 : sentence_transformers
!pip install sentence_transformers

In [ ]:
### 필요한 라이브러리 임폴트
from sentence_transformers import SentenceTransformer

### 한글 문장 유사도 측정

In [ ]:
### 문장 임베딩 벡터를 추출 --> 사전 학습된 한국어 SentenceTransformer(Sentence-BERT) 모델 생성
model_name='ddobokki/klue-roberta-base-nli-sts'
model_kor = SentenceTransformer(model_name) 

In [ ]:
### 한글 텍스트 데이터 생성
ko_sentences = ["직원이 무단 퇴사를 했는데 손해 배상 청구할 수 있나요?", "무단 퇴사한 직원에 대한 손해 배상 청구가 가능한가요?"]

In [ ]:
### 문장 임베딩 벡터 생성하기
embeddings = model_kor.encode(ko_sentences)

# 결과 확인하기
print(f'실습용 문장의 임베딩 벡터의 모양 : {embeddings.shape}')
print('-'*80)
print(f'실습용 문장 1의 임베딩 벡터 : \n{embeddings[0]}')
print('-'*80)
print(f'실습용 문장 2의 임베딩 벡터 : \n{embeddings[1]}')

실습용 문장의 임베딩 벡터의 모양 : (2, 768)
--------------------------------------------------------------------------------
실습용 문장 1의 임베딩 벡터 : [-4.99942571e-01 -3.59200835e-01 -7.38402531e-02  4.84219283e-01
 -4.96614248e-01  5.82403541e-01 -4.56283726e-02 -3.81823957e-01
 -3.94545138e-01  2.18352810e-01  2.40236789e-01 -6.53119922e-01
  1.17322057e-01 -4.41113472e-01 -8.18792358e-03 -2.16762990e-01
  1.42985918e-02 -9.46455747e-02  1.55718908e-01 -1.03794202e-01
 -5.95203459e-01 -5.41155756e-01 -6.22601569e-01 -1.00601912e+00
 -2.20479086e-01 -1.32809609e-01 -4.36401814e-02 -4.01161388e-02
  5.56914985e-01  7.56343365e-01  6.72926083e-02  8.65490139e-01
  4.12386395e-02  2.79035717e-01 -1.98161840e-01 -5.00128530e-02
  3.10567111e-01 -3.46614331e-01 -6.20579302e-01  6.81772709e-01
  8.81860033e-02  2.54626155e-01 -4.60292697e-01 -1.45168155e-01
 -6.55795122e-03 -2.85244942e-01  6.48579188e-03  3.51094782e-01
  9.55613628e-02 -1.56446829e-01 -1.90832376e-01 -3.73097628e-01
  2.39245042e-01  3.94674

In [ ]:
### 코싸인 유사도 측정

# 필요한 라이브러리 임폴트
from sklearn.metrics.pairwise import cosine_similarity

# 1차원 배열 --> 2차원 배열로 변환
embedding1 = embeddings[0].reshape((1,768))
embedding2 = embeddings[1].reshape((1,768))

# cosine_similarity() 사용
similarity = cosine_similarity(embedding1, embedding2)

# 결과 확인하기
print(similarity)

[[0.96061534]]


### 영어 문장 유사도 측정

In [ ]:
### SentenceTransformer 모델 객체 생성
model_name = 'sentence-transformers/all-MiniLM-L12-v2'
model_eng = SentenceTransformer(model_name)

In [ ]:
### 영문 텍스트 데이터 생성
en_sentences = ["What should I do to be a great scientist?", "How can I be a good scientist?"]
print(en_sentences)

['What should I do to be a great scientist?', 'How can I be a good scientist?']


In [ ]:
### 문장 임베딩 벡터 생성
embeddings = model_eng.encode(en_sentences)

# 결과 확인하기
print(f'실습용 문장의 임벡딩 벡터의 모양 : {embeddings.shape}')
print('-'*80)
print(f'실습용 문장 1의 임벡딩 벡터 : \n{embeddings[0]}')
print('-'*80)
print(f'실습용 문장 2의 임베딩 벡터 : \n{embeddings[1]}')

실습용 문장의 임벡딩 벡터의 모양 : (2, 384)
--------------------------------------------------------------------------------
실습용 문장 1의 임벡딩 벡터 : 
[ 2.22636163e-02  8.50509629e-02  7.91068599e-02 -6.84864074e-03
 -1.46627463e-02 -6.85858354e-02  2.64204349e-02  6.64388910e-02
 -4.24608253e-02 -3.75801958e-02  1.80893745e-02 -9.48859900e-02
 -4.75542396e-02  7.65434429e-02 -3.93009633e-02  2.58018598e-02
 -7.41134211e-02  5.87385967e-02  3.13342884e-02 -7.86113665e-02
 -6.38961121e-02  4.31189574e-02  6.02598302e-03  1.21794816e-03
 -5.90102486e-02  8.42711702e-02 -2.48904601e-02 -6.01979792e-02
  2.75624543e-02 -5.94474003e-02 -8.06285942e-04 -7.62991086e-02
  1.78552195e-02  2.06335429e-02 -3.27370800e-02  4.25934419e-02
  6.07815199e-02 -2.56904643e-02  5.79138026e-02  5.28666861e-02
  9.59739275e-03 -4.70351726e-02  2.61405464e-02 -9.10800532e-04
  8.14124290e-03 -1.69612709e-02  2.88743880e-02 -1.83994416e-03
  3.87182906e-02  3.14612091e-02 -5.87458573e-02 -7.69814849e-02
 -1.39820710e-01 -6.1561

In [ ]:
### 코사인 유사도 측정하기

# 1차원 배열 --> 2차원 배열로 변환
embedding1 = embeddings[0].reshape((1,384))
embedding2 = embeddings[1].reshape((1,384))

# cosine_similarity() 함수 이용
similarity = cosine_similarity(embedding1, embedding2)
print(similarity)

[[0.8954653]]


### 영어 / 한글 문장 유사도 측정

In [ ]:
### 다국어 지원 Sentence-BERT 모델 생성
model_name='sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'
model_multi = SentenceTransformer(model_name)

In [ ]:
### 텍스트 데이터 생성
sentences = ['What should I do to be a great scientist?', '훌륭한 과학자가 되려면 어떻게 해야 할까요?']

In [ ]:
### 문장 임베딩 벡터 생성하기
embeddings = model_multi.encode(sentences)

# 결과 확인하기
print(f'실습용 문장의 임베딩 벡터의 모양 = {embeddings.shape}')
print('-'*80)
print(f'실습용 문장 1의 임베딩 벡터의 모양 : {embeddings[0].shape}')
print('-'*80)
print(f'실습용 문장 2의 임베딩 벡터의 모양 : {embeddings[1].shape}')

실습용 문장의 임베딩 벡터의 모양 = (2, 384)
--------------------------------------------------------------------------------
실습용 문장 1의 임베딩 벡터의 모양 : (384,)
--------------------------------------------------------------------------------
실습용 문장 2의 임베딩 벡터의 모양 : (384,)


In [ ]:
### 코사인 유사도 측정

# 1차원 배열 --> 2차원 배열로 변환
embedding1 = embeddings[0].reshape((1,384))
embedding2 = embeddings[1].reshape((1,384))

# cosine_similarity() 사용
similarity = cosine_similarity(embedding1, embedding2)
print(similarity)

[[0.9493034]]


## 문장 유사도를 이용한 추천 시스템

In [ ]:
### 구글 서버와 내드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
### 작업 디렉토리 변경
%cd '/content/drive/MyDrive/KDT/비정형텍스트분석'

/content/drive/MyDrive/KDT/비정형텍스트분석


In [ ]:
### 필요한 라이브러리 임폴트
import pandas as pd
from sklearn.metrics.pairwise import linear_kernel

In [ ]:
### pd.read_csv() --> DataFrame 자료형 생성
file_path = 'movies_metadata.csv'
df = pd.read_csv(file_path)
print(df)
print('-'*80)
df.info()

<ipython-input-22-d41254bad4f2>:3: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)


       adult                              belongs_to_collection    budget  \
0      False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1      False                                                NaN  65000000   
2      False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3      False                                                NaN  16000000   
4      False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
...      ...                                                ...       ...   
45461  False                                                NaN         0   
45462  False                                                NaN         0   
45463  False                                                NaN         0   
45464  False                                                NaN         0   
45465  False                                                NaN         0   

                                                  genres  \
0      [{'id': 

In [ ]:
### 줄거리(overview), 제목(title) 컬럼을 기준 --> 누락 데이터 제거

# fancy indexing
data = df[['overview', 'title']]

# 누락 데이터 제거
df_movies = data.dropna()

# 결과 확인하기
print(df_movies)
print('-'*80)
df_movies.info()

                                                overview  \
0      Led by Woody, Andy's toys live happily in his ...   
1      When siblings Judy and Peter discover an encha...   
2      A family wedding reignites the ancient feud be...   
3      Cheated on, mistreated and stepped on, the wom...   
4      Just when George Banks has recovered from his ...   
...                                                  ...   
45461        Rising and falling between a man and woman.   
45462  An artist struggles to finish his work while a...   
45463  When one of her hits goes wrong, a professiona...   
45464  In a small town live two brothers, one a minis...   
45465  50 years after decriminalisation of homosexual...   

                             title  
0                        Toy Story  
1                          Jumanji  
2                 Grumpier Old Men  
3                Waiting to Exhale  
4      Father of the Bride Part II  
...                            ...  
45461               

In [ ]:
### 누락 데이터 제거 후 인덱스 재조정 --> reset_index(drop=True)
df_movies.reset_index(drop=True, inplace=True)

# 결과 확인하기
print(df_movies)

                                                overview  \
0      Led by Woody, Andy's toys live happily in his ...   
1      When siblings Judy and Peter discover an encha...   
2      A family wedding reignites the ancient feud be...   
3      Cheated on, mistreated and stepped on, the wom...   
4      Just when George Banks has recovered from his ...   
...                                                  ...   
44501        Rising and falling between a man and woman.   
44502  An artist struggles to finish his work while a...   
44503  When one of her hits goes wrong, a professiona...   
44504  In a small town live two brothers, one a minis...   
44505  50 years after decriminalisation of homosexual...   

                             title  
0                        Toy Story  
1                          Jumanji  
2                 Grumpier Old Men  
3                Waiting to Exhale  
4      Father of the Bride Part II  
...                            ...  
44501               

In [ ]:
### data의 수를 10000개로 축소
df_data = df_movies.iloc[:10000, :] 

# 결과 확인하기
print(df_data)

                                               overview  \
0     Led by Woody, Andy's toys live happily in his ...   
1     When siblings Judy and Peter discover an encha...   
2     A family wedding reignites the ancient feud be...   
3     Cheated on, mistreated and stepped on, the wom...   
4     Just when George Banks has recovered from his ...   
...                                                 ...   
9995  In the peaceful countryside, Vassily opposes t...   
9996  Francisco is rich, rather strict on principles...   
9997  Cashier Maurice Legrand is married to Adele, a...   
9998  While Erendira, a beautiful teenage girl, has ...   
9999  This period drama frames the tumultuous affair...   

                                         title  
0                                    Toy Story  
1                                      Jumanji  
2                             Grumpier Old Men  
3                            Waiting to Exhale  
4                  Father of the Bride Part II

In [ ]:
### SentenceTransformer 모델 객체 생성
model_name = 'sentence-transformers/all-MiniLM-L12-v2'
model = SentenceTransformer(model_name)

In [ ]:
### 문장 임베딩 벡터 생성

# 필요한 라이브리 임폴트
import numpy as np

# overview 컬럼 --> 배열 생성
sentences = df_data.overview.values

# model.encode() 함수 사용
embeddings = model.encode(sentences)

# 결과 확인하기
print(f'생성된 문장 임베딩 행렬의 모양 : {embeddings.shape}')
print('-'*80)
print(f'문장 1개의 임베딩 벡터의 모양 : {embeddings[0].shape}')

생성된 문장 임베딩 벡터의 모양 : (10000, 384)
--------------------------------------------------------------------------------
문장 1개의 임베딩 벡터의 모양 : (384,)


In [ ]:
### 문장 임베딩 행렬 저장
np.save('embeddings.npy', embeddings)

In [ ]:
### linear_kernel() 함수 --> 10000개의 영화 줄거리 각각에 대해서 코사인 유사도 측정
similarity = linear_kernel(embeddings, embeddings)

# 결과 확인하기
print(f'유사도 측정의 결과 : \n{similarity}')
print('-'*80)
print(f'유사도 측정의 결과 값의 모댱 : {similarity.shape}')
print('-'*80)
print(f'Toy Story에 대한 유사도 측정의 결과 : \n{similarity[0]}')

유사도 측정의 결과 : [[1.0000001  0.33839953 0.12692964 ... 0.12217252 0.17416474 0.06714299]
 [0.33839953 1.0000002  0.2637778  ... 0.1654589  0.3252555  0.16340762]
 [0.12692964 0.2637778  0.9999999  ... 0.24624068 0.2797468  0.14819568]
 ...
 [0.12217252 0.1654589  0.24624068 ... 1.0000001  0.21591775 0.0477701 ]
 [0.17416474 0.3252555  0.2797468  ... 0.21591775 1.         0.18749893]
 [0.06714299 0.16340762 0.14819568 ... 0.0477701  0.18749893 0.9999999 ]]
--------------------------------------------------------------------------------
유사도 측정의 결과 값의 모댱 : (10000, 10000)
--------------------------------------------------------------------------------
Toy Story에 대한 유사도 측정의 결과 : 
[1.0000001  0.33839953 0.12692964 ... 0.12217252 0.17416474 0.06714299]


In [ ]:
### 코사인 유사도 --> 데이터프레임 생성
columns = df_data.title.values
index = df_data.title.values

# 데이터프레임 생성
df_sim = pd.DataFrame(data=similarity, columns=columns, index=index)

# 결과 확인하기
df_sim

Toy Story   Jumanji  \
Toy Story                                  1.000000  0.338400   
Jumanji                                    0.338400  1.000000   
Grumpier Old Men                           0.126930  0.263778   
Waiting to Exhale                          0.175748  0.205652   
Father of the Bride Part II                0.137818  0.144077   
...                                             ...       ...   
Earth                                      0.035998 -0.014982   
Él                                         0.183392  0.177061   
La Chienne                                 0.122173  0.165459   
Eréndira                                   0.174165  0.325256   
The Private Lives of Elizabeth and Essex   0.067143  0.163408   

                                          Grumpier Old Men  Waiting to Exhale  \
Toy Story                                         0.126930           0.175748   
Jumanji                                           0.263778           0.205652   
Grumpier Old Men                                  1.000000           0.360031   
Waiting to Exhale                                 0.360031           1.000000   
Father of the Bride Part II                       0.175603           0.204694   
...                                                    ...                ...   
Earth                                             0.081070           0.156300   
Él                                                0.420658           0.390909   
La Chienne                                        0.246241           0.197444   
Eréndira                                          0.279747           0.306730   
The Private Lives of Elizabeth and Essex          0.148196           0.167567   

                                          Father of the Bride Part II  \
Toy Story                                                    0.137818   
Jumanji                                                      0.144077   
Grumpier Old Men                                             0.175603   
Waiting to Exhale                                            0.204694   
Father of the Bride Part II                                  1.000000   
...                                                               ...   
Earth                                                        0.023103   
Él                                                           0.253434   
La Chienne                                                   0.131023   
Eréndira                                                     0.240259   
The Private Lives of Elizabeth and Essex                     0.088746   

                                              Heat   Sabrina  Tom and Huck  \
Toy Story                                 0.224320  0.183411      0.304267   
Jumanji                                   0.294304  0.253075      0.397237   
Grumpier Old Men                          0.211339  0.314121      0.291589   
Waiting to Exhale                         0.286783  0.332937      0.295825   
Father of the Bride Part II               0.089654  0.117296      0.065354   
...                                            ...       ...           ...   
Earth                                    -0.033135  0.104973      0.045792   
Él                                        0.247657  0.311852      0.195511   
La Chienne                                0.212082  0.328271      0.201282   
Eréndira                                  0.258495  0.177591      0.255010   
The Private Lives of Elizabeth and Essex  0.079199  0.091832      0.091884   

                                          Sudden Death  GoldenEye  ...  \
Toy Story                                     0.143974   0.111093  ...   
Jumanji                                       0.254173   0.167929  ...   
Grumpier Old Men                              0.186269   0.203596  ...   
Waiting to Exhale                             0.280217   0.182333  ...   
Father of the Bride Part II                   0.216099   0.111157  ...   
...                           

In [ ]:
### 특정 영화 기준 --> 줄거리가 유사한 영호 추천 함수 생성

def recommend(title):
    top10 = df_sim[title].sort_values(ascending=False)[1:11]
    return top10

# 결과 확인하기
top10 = recommend('GoldenEye')
print(f'결과 확인하기 : \n{top10}')

결과 확인하기 : 
Live and Let Die               0.628484
Octopussy                      0.618100
Never Say Never Again          0.605646
The Living Daylights           0.594822
The Man with the Golden Gun    0.591555
Goldfinger                     0.573768
Casino Royale                  0.573743
Licence to Kill                0.571086
Die Another Day                0.567978
Dr. No                         0.553751
Name: GoldenEye, dtype: float32
