## LGBMClassifier 모델을 이용한 텍스트 유사도 분석 모델

### 저장된 데이터 불러오기 

In [ ]:
### 구글 서버와 내 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
### 작업 디렉토리 변경
%cd '/content/drive/MyDrive/KDT/비정형텍스트분석'

/content/drive/MyDrive/KDT/비정형텍스트분석


In [ ]:
### 필요한 라이브러리 임폴트
import numpy as np

In [ ]:
### 저장된 파일 불러오기
q1_data = np.load('q1_data.npy')
q2_data = np.load('q2_data.npy')
labels = np.load('labels.npy')

# 결과 확인하기
print(q1_data[0])
print('-'*80)
print(q2_data[0])
print('-'*80)
print(labels[0])

[  11   53   80 1721   16    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0]
--------------------------------------------------------------------------------
[   2 1721  597    9   15  866    1   92    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0]
--------------------------------------------------------------------------------
0


### 학습용 / 평가용 데이터 생성하기

In [ ]:
### q1_data와 q2_data --> 1개의 데이터

data_array = q1_data + q2_data

# 결과 확인하기
print(data_array)

[[   13  1774   677 ...     0     0     0]
 [    4    14  4359 ...     0     0     0]
 [    4     6  5732 ...     0     0     0]
 ...
 [    8    32   141 ...     0     0     0]
 [    4    42 16198 ...     0     0     0]
 [   12    34   543 ...     0     0     0]]


In [ ]:
### train_test_split() 사용

# 필요한 라이브러리 임폴트
from sklearn.model_selection import train_test_split

# 학습용 / 평가용 데이터로 분할
X_train, X_test, y_train, y_test = train_test_split(data_array, labels, test_size=0.2, random_state=99)

# 결과 확인하기
print(f'학습용 데이터의 모양 : {X_train.shape}')
print(f'학습용 레이블의 모양 : {y_train.shape}')
print('-'*80)
print(f'평가용 데이터의 모양 : {X_test.shape}')
print(f'평가용 레이블의 모양 : {y_test.shape}')

학습용 데이터의 모양 : (238820, 31)
학습용 레이블의 모양 : (238820,)
--------------------------------------------------------------------------------
평가용 데이터의 모양 : (59706, 31)
평가용 레이블의 모양 : (59706,)


### 모델 생성 / 학습 / 평가

In [ ]:
### 모델 생성

# 필요한 라이브러리 임폴트
from lightgbm import LGBMClassifier

# 기본 모델 생성
lgbm = LGBMClassifier(random_state=99)

# n_estimators=300, learning_rate=0.3 모델 생성
lgbm_300 = LGBMClassifier(n_estimators=300, learning_rate=0.3, random_state=99)

In [ ]:
### 기본 모델 학습
lgbm.fit(X_train, y_train)

LGBMClassifier(random_state=99)

In [ ]:
### 기본 모델 --> 평가용 데이터를 이용한 예측
pred_test = lgbm.predict(X_test)

In [ ]:
### 기본 모델에 대한 정확도 평가

# 필요한 라이브러리 임폴트
from sklearn.metrics import accuracy_score

# 평가용 데이터를 이용한 평가
accuracy_test = accuracy_score(y_test, pred_test)

# 결과 확인하기
print(accuracy_test)

0.7084380129300237
