## Pandas

In [ ]:
### pandas 라이브러리 설치

!pip install pandas

Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main.py", line 9, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/autocompletion.py", line 10, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/cmdoptions.py", line 24, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/usr/local/lib/python3.9/dist-packages/pip/_internal/cli/progress_bars.py", line 9, in <module>
    from pip._vendor.rich.progress import (
  File "/usr/local/lib/python3.9/dist-packages/pip/_vendor/rich/progress.py", line 360, 

In [ ]:
### 필요한 라이브러리 임폴트

import pandas as pd

In [ ]:
### 리스트 자료형 데이터를 이용해서 Series 자료형 생성

data = [9904312, 3448737, 2890451, 2466052]
population = pd.Series(data)
print(population)

0    9904312
1    3448737
2    2890451
3    2466052
dtype: int64


In [ ]:
### 인덱스를 지정해서 Series 자료형 생성

data = [9904312, 3448737, 2890451, 2466052]
index = ['서울','부산','인천','대구']
population = pd.Series(data=data, index=index)

# 결과 확인하기
print(population)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [ ]:
#### dict 자료형을 이용하여 Series 자료형 생성

data = {"서울": 9904312, "부산": 3448737, "인천": 2890451, "대구": 2466052}
population = pd.Series(data)

# 결과 확인하기
print(population)

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [ ]:
### Series 데이터 확인

# values 확인
print(population.values)

print('-'*80)

# index 확인
print(population.index)

print('-'*80)

# dtype 확인
print(population.dtype)

[9904312 3448737 2890451 2466052]
--------------------------------------------------------------------------------
Index(['서울', '부산', '인천', '대구'], dtype='object')
--------------------------------------------------------------------------------
int64


In [ ]:
### 인덱싱

'''
1. index : 숫자, 문자열 인덱스를 이용하여 인덱싱
2. fancy indexing : 동시에 여러 개의 데이터를 인덱싱
'''

# Series 자료형 생성 --> population 활용
print(population)

print('-'*80)

# index 1번으로 인덱싱
print(f'두번째 원소 인덱싱 = {population[1]}')
print(f'두번째 원소 인덱싱 = {population["부산"]}')

print('-'*80)

# index 3번으로 인덱싱
print(f'네번째 원소 인덱싱 = {population[3]}')
print(f'네번째 원소 인덱싱 = {population["대구"]}')

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64
--------------------------------------------------------------------------------
두번째 원소 인덱싱 = 3448737
두번째 원소 인덱싱 = 3448737
--------------------------------------------------------------------------------
네번째 원소 인덱싱 = 2466052
네번째 원소 인덱싱 = 2466052


In [ ]:
### 한번에 여러개를 리스트 형식을 이용하여 인덱싱 --> "fancy indexing"

'''
변수명[[index3, index0, index2]] --> 사용자가 지정한 index의 순서대로 값을 추출 가능
'''

# 리스트의 형식 [0, 3, 1]
fancy = population[[0, 3, 1]]
print(f'팬시 인덱싱의 결과 : \n{fancy}')

print('-'*80)

# 문자열 인덱스 --> fancy 인덱싱 가능
fancy = population[['서울', '인천', '부산']]
print(f'팬시 인덱싱의 결과 : \n{fancy}')

팬시 인덱싱의 결과 : 
서울    9904312
대구    2466052
부산    3448737
dtype: int64
--------------------------------------------------------------------------------
팬시 인덱싱의 결과 : 
서울    9904312
인천    2890451
부산    3448737
dtype: int64


In [ ]:
### 슬라이싱

'''
1. 숫자 인덱스 : [start:end] --> start : end -1
2. 문자열 인덱스 : [start:end] --> start : end (이유 : 문자열 -1 (x))
'''

# 숫자 인덱스 이용
sliced = population[1:3]
print(sliced)

print('-'*80)

# 문자 인덱스 이용
sliced = population["부산":"대구"]
print(sliced)

부산    3448737
인천    2890451
dtype: int64
--------------------------------------------------------------------------------
부산    3448737
인천    2890451
대구    2466052
dtype: int64


In [ ]:
### 딕셔너리 자료형으로 DataFrame 자료형 데이터 생성하기

# python dict 자료형 데이터 생성
pop_dict = {'2015':[9904312, 3448737, 2890451, 2466052], 
            '2010':[9631482, 3393191, 2632035, 2431774]}

# DataFrame 자료형 생성
df = pd.DataFrame(data=pop_dict)

# 결과 확인하기
print(df)

      2015     2010
0  9904312  9631482
1  3448737  3393191
2  2890451  2632035
3  2466052  2431774


In [ ]:
### 문자열의 인덱스를 추가 1

pop_dict = {'2015':[9904312, 3448737, 2890451, 2466052], 
            '2010':[9631482, 3393191, 2632035, 2431774]}
index = ['서울', '부산', '인천', '대구']

df = pd.DataFrame(data=pop_dict, index=index)

# 결과 확인하기
print(df)

       2015     2010
서울  9904312  9631482
부산  3448737  3393191
인천  2890451  2632035
대구  2466052  2431774


In [ ]:
### 문자열의 인덱스를 추가 2

pop_info = {'2015':[9904312, 3448737, 2890451, 2466052], 
            '2010':[9631482, 3393191, 2632035, 2431774]}

df = pd.DataFrame(data=pop_info)

# 데이터프레임 자료형 생성 후 문자열 인덱스 추가
df.index = ['서울', '부산', '인천', '대구']

# 결과 확인하기
print(df)

       2015     2010
서울  9904312  9631482
부산  3448737  3393191
인천  2890451  2632035
대구  2466052  2431774


In [ ]:
### Series 자료형으로 DataFrame 자료형 만들기 --> 자료형 변환 가능

df = pd.DataFrame(data=population, columns=['population'])

print(df)

    population
서울     9904312
부산     3448737
인천     2890451
대구     2466052


In [ ]:
### test1
import pandas as pd

data = ['가','나','다','라','마']
res = pd.Series(data)
print(res)

0    가
1    나
2    다
3    라
4    마
dtype: object


In [ ]:
### test2

data = [10,20,30,40,50]
index = ['가','나','다','라','마']
sample = pd.Series(data, index)
print(sample)

가    10
나    20
다    30
라    40
마    50
dtype: int64


In [ ]:
### test3

print(sample[['나', '라']])

나    20
라    40
dtype: int64


In [ ]:
### test4

data = {'food':['KFC', 'McDonald', 'SchoolFood'], 'price':[1000,2000,2500], 'rating':[4.5, 3.9, 4.2]}
df = pd.DataFrame(data)
print(df)

         food  price  rating
0         KFC   1000     4.5
1    McDonald   2000     3.9
2  SchoolFood   2500     4.2


In [ ]:
### DataFrame 자료형 --> 컬럼, 값, 인덱스 확인하기

# 데이터 확인하기
print(df)

print('-'*80)

# column 정보 확인
cols = df.columns
print(f'컬럼 정보 : {cols}')

print('-'*80)

# 컬럼의 값 정보 확인
vals = df.values
print(f'컬럼의 값 : \n{vals}')

print('-'*80)

# 행(row) index 정보 확인
ind = df.index
print(f'행의 인덱스 : {ind}')

print('-'*80)
types = df.dtypes
print(f'컬럼 별 데이터의 자료형 : \n{types}')

    population
서울     9904312
부산     3448737
인천     2890451
대구     2466052
--------------------------------------------------------------------------------
컬럼 정보 : Index(['population'], dtype='object')
--------------------------------------------------------------------------------
컬럼의 값 : 
[[9904312]
 [3448737]
 [2890451]
 [2466052]]
--------------------------------------------------------------------------------
행의 인덱스 : Index(['서울', '부산', '인천', '대구'], dtype='object')
--------------------------------------------------------------------------------
컬럼 별 데이터의 자료형 : 
population    int64
dtype: object


In [ ]:
### DataFrame --> 새로운 컬럼 추가 / 수정

df['2005'] = [9762546,3512547,2517680,2456016]
print(df)

print('-'*80)

# 컬럼의 값 수정
df['2005'] = ["","","",""]
print(df)

print('-'*80)

df['2005'] = [9762546,3512547,2517680,2456016]
print(df)

print('-'*80)

# 인덱스 수정
df.index = ['Seoul', 'Busan', 'Inchon', 'Deagu']
print(df)

       2015     2010     2005
서울  9904312  9631482  9762546
부산  3448737  3393191  3512547
인천  2890451  2632035  2517680
대구  2466052  2431774  2456016
--------------------------------------------------------------------------------
       2015     2010 2005
서울  9904312  9631482     
부산  3448737  3393191     
인천  2890451  2632035     
대구  2466052  2431774     
--------------------------------------------------------------------------------
       2015     2010     2005
서울  9904312  9631482  9762546
부산  3448737  3393191  3512547
인천  2890451  2632035  2517680
대구  2466052  2431774  2456016
--------------------------------------------------------------------------------
           2015     2010     2005
Seoul   9904312  9631482  9762546
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
Deagu   2466052  2431774  2456016


In [ ]:
### 인덱싱

# 데이터 확인
print(df)

print('-'*80)

# '2015' 컬럼에 대해서 인덱싱 --> '열' 인덱싱
print(df['2015'])

print('-'*80)

# '행' 인덱싱 --> 행 인덱스 : 문자 + 숫자
df[0] # 오류

           2015     2010     2005
Seoul   9904312  9631482  9762546
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
Deagu   2466052  2431774  2456016
--------------------------------------------------------------------------------
Seoul     9904312
Busan     3448737
Inchon    2890451
Deagu     2466052
Name: 2015, dtype: int64
--------------------------------------------------------------------------------


KeyError: ignored

In [ ]:
### fancy 인덱싱 --> 컬럼 --> 리스트의 형태로

# 2015, 2010 동시에 인덱싱
fancy = df[['2015', '2010']]
print(f'2개의 컬럼을 동시에 인덱싱을 할 경우, 결과 값 : \n{fancy}')

2개의 컬럼을 동시에 인덱싱을 할 경우, 결과 값 : 
           2015     2010
Seoul   9904312  9631482
Busan   3448737  3393191
Inchon  2890451  2632035
Deagu   2466052  2431774


In [ ]:
### 슬라이싱

# 데이터 확인
print(df)

print('-'*80)

# 행 슬라이싱 --> 행 인덱스 --> 기본 : 번호
sliced = df[0:2]
print(sliced)

print('-'*80)

# 행 슬라이싱 --> 행 인덱스 --> 문자
sliced = df['Seoul' : 'Inchon']
print(sliced)

print('-'*80)

# 컬럼 --> 슬라이싱
col_sliced = df['2015':'2010']
print(f'컬럼에 대한 슬라이싱 : {col_sliced}')

           2015     2010     2005
Seoul   9904312  9631482  9762546
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
Deagu   2466052  2431774  2456016
--------------------------------------------------------------------------------
          2015     2010     2005
Seoul  9904312  9631482  9762546
Busan  3448737  3393191  3512547
--------------------------------------------------------------------------------
           2015     2010     2005
Seoul   9904312  9631482  9762546
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
--------------------------------------------------------------------------------


KeyError: ignored

In [ ]:
### loc 인덱서 --> df.loc[행, 열]

# 데이터 확인
print(df)

print('-'*80)

# 행 : 부산에서 인천까지, 열 : 2015년부터 2010년까지
sliced1 = df.loc['Busan':'Inchon', '2015':'2010']
print(sliced1)

print('-'*80)

# 행 : 부산에서 인천까지, 열 : 전체
sliced2 = df.loc['Busan':'Inchon', :]
print(sliced2)

print('-'*80)

# 행 : 전체 행, 열 : 2015 --> '2015' 행 인덱싱과 같은 결과
sliced3 = df.loc[:, '2015']
print(sliced3)

print('-'*80)

# 열 인덱싱
print(df['2015'])

           2015     2010     2005
Seoul   9904312  9631482  9762546
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
Deagu   2466052  2431774  2456016
--------------------------------------------------------------------------------
           2015     2010
Busan   3448737  3393191
Inchon  2890451  2632035
--------------------------------------------------------------------------------
           2015     2010     2005
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
--------------------------------------------------------------------------------
Seoul     9904312
Busan     3448737
Inchon    2890451
Deagu     2466052
Name: 2015, dtype: int64
--------------------------------------------------------------------------------
Seoul     9904312
Busan     3448737
Inchon    2890451
Deagu     2466052
Name: 2015, dtype: int64


In [ ]:
### iloc 인덱서

# 데이터 확인
print(df)

print('-'*80)

# 행 : 첫번째부터 두번째 행, 열 : 두번째부터 끝까지
sliced = df.iloc[0:2, 1:]
print(sliced)

           2015     2010     2005
Seoul   9904312  9631482  9762546
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
Deagu   2466052  2431774  2456016
--------------------------------------------------------------------------------
          2010     2005
Seoul  9631482  9762546
Busan  3393191  3512547


In [ ]:
### 비교 연산자

# 두 변수 설정
a = 10
b = 3

# 두 변수의 비교
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)
print(a == b)
print(a != b)

True
False
True
False
False
True


In [ ]:
### 논리 연산자

# 두 변수 설정
a = 10
b = 3

# & 연산자 : True and True --> True
condition1 = (a > b) & (a != b)
print(condition1)

print('-'*80)

# | 연산자 : True | False --> True
condition2 = (a > b) | (a == b)
print(condition2)

True
--------------------------------------------------------------------------------
True


In [ ]:
### boolean 인덱싱

# 데이터 확인
print(df)

print('-'*80)

# 비교 연산자 적용
condition = (df['2015'] >= 3000000)
print(condition)
print(type(df['2015']))
print(type(df['2015'] >= 3000000))

print('-'*80)

# 비교 연산의 결과 --> 인덱싱 적용 --> fancy 인덱싱
print(df['2015'][condition])

print('-'*80)

# 논리 연산자 적용 -> 조건에 만족하는 행 추출
condition2 = (df['2015'] >= 3000000) & (df['2010'] >= 4000000)
print(f'condition2 결과 확인 : \n{condition2}')

           2015     2010     2005
Seoul   9904312  9631482  9762546
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
Deagu   2466052  2431774  2456016
--------------------------------------------------------------------------------
Seoul      True
Busan      True
Inchon    False
Deagu     False
Name: 2015, dtype: bool
<class 'pandas.core.series.Series'>
<class 'pandas.core.series.Series'>
--------------------------------------------------------------------------------
Seoul    9904312
Busan    3448737
Name: 2015, dtype: int64
--------------------------------------------------------------------------------
condition2 결과 확인 : 
Seoul      True
Busan     False
Inchon    False
Deagu     False
dtype: bool


In [ ]:
### boolean 인덱싱 보충

# 데이터프레임 자료형 데이터
print(df)

print('-'*80)

# 데이터프레임 --> '열'인덱싱 --> 시리즈 자료형 생성
myseries = df['2015']
print(f'자료형 : {type(myseries)}') 
print('-'*80)
print(f'값 : \n{myseries}')

print('-'*80)

# 2015 컬럼의 값과 3000000 값의 비교 연산
vals = myseries.values
print(f'2015 컬럼의 값 : {vals}')

print('-'*80)

res = []

for val in vals:
    print(f'val = {val}')
    # 비교 연산
    mid = (val >= 3000000)
    print(f'mid = {mid}')
    res.append(mid)

print(f'result = {res}')

print('-'*80)

# series 자료형 --> 컬럼 1개 --> '행' 인덱싱 만 존재!
fires = myseries[0]
print(f'0번째 인덱스에 대한 인덱싱의 결과 = {myseries[0]}')

print('-'*80)

# fancy 인덱싱 --> df['col][[index1, index2,...]]
fancy = myseries[[0, 1]]
print(f'fancy 인덱싱에 대한 결과 : \n{fancy}')

print('-'*80)

condition = [0, 1]
fancy1 = myseries[condition]
print(f'fancy 인덱싱에 대한 결과 : \n{fancy1}')

print('-'*80)

fancy2 = myseries[res]
print(f'boolean 인덱싱에 대한 결과 : \n{fancy2}')

           2015     2010     2005
Seoul   9904312  9631482  9762546
Busan   3448737  3393191  3512547
Inchon  2890451  2632035  2517680
Deagu   2466052  2431774  2456016
--------------------------------------------------------------------------------
자료형 : <class 'pandas.core.series.Series'>
--------------------------------------------------------------------------------
값 : 
Seoul     9904312
Busan     3448737
Inchon    2890451
Deagu     2466052
Name: 2015, dtype: int64
--------------------------------------------------------------------------------
2015 컬럼의 값 : [9904312 3448737 2890451 2466052]
--------------------------------------------------------------------------------
val = 9904312
mid = True
val = 3448737
mid = True
val = 2890451
mid = False
val = 2466052
mid = False
result = [True, True, False, False]
--------------------------------------------------------------------------------
0번째 인덱스에 대한 인덱싱의 결과 = 9904312
------------------------------------------------------------------

In [ ]:
### list 자료형 데이터를 사용해서 DataFrame 자료형 생성

# 데이터, 인덱스, 컬럼 생성
mydata = [[9904312, 3448737, 2890451, 2455052],
          [9632482, 3393191, 2632035, 2431774]]

myindex = ['2015', '2010']

mycolumns = ['서울', '부산', '인천', '대구']

# DataFrame 자료형 생성
df = pd.DataFrame(mydata, myindex, mycolumns)

# 결과 확인하기
print(df)

           서울       부산       인천       대구
2015  9904312  3448737  2890451  2455052
2010  9632482  3393191  2632035  2431774


In [ ]:
### csv 파일 처리(1)

# read_csv(file_path, encoding='cp949')
df = pd.read_csv('dataframe.csv', encoding='cp949')

# 결과 확인하기
print(df)

     Unnamed: 0                                           sentence  label
0             0  본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...      1
1             1  본 발명은 타히보 추출물 및 팔각회향을 유효성분으로 포함하는 면역 증진용 조성물에 ...      1
2             2  본 출원은 신규한 터키 겨우살이의 추출물, 렉틴 및 상기 추출물 또는 렉틴의 제조방...      1
3             3  아로니아(Aronia) 열매 추출물, 댕댕이나무(Lonicera caerulea) ...      1
4             4  본 발명의 청각 추출물 및 홍삼 추출물을 포함하는 선천성 면역 증진용 조성물에 관한...      1
..          ...                                                ...    ...
145         145  본 발명은 엉겅퀴(Cirsium japonicum var. ussuriense) 잎...      1
146         146  본 발명은 어성초 초임계 추출물을 유효성분으로 함유하는 관절염 질환의 예방 및 치료...      1
147         147  본 발명은 항염증 활성과 파골세포 억제 효과를 갖는 두충 추출물, 상기 추출물을 유...      1
148         148  본 발명은 유효성분으로서 다음과 같은 진세노사이드 함량을 나타내는 홍삼 발효액을 포...      1
149         149  본 발명은 전통 한의약 이론에 근거하여 한방의 복합 생약추출물에 발효기술을 이용하여...      1

[150 rows x 3 columns]


In [ ]:
### csv 파일 처리(2)

# 구글 서버와 내 드라이브 연결
from google.colab import drive
drive.mount('/content/drive')

# 현재 작업 경로
%cd '/content/drive/MyDrive/KDT/정형데이터분석시각화'

# 파일 경로 설정
file_path = 'dataframe.csv'

# read_csv(file_path, encoding='cp949, index_col=0)
df = pd.read_csv(file_path, encoding='cp949', index_col=0)

# 결과 확인하기
print(df)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/drive/MyDrive/KDT/정형데이터분석시각화
                                              sentence  label
0    본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...      1
1    본 발명은 타히보 추출물 및 팔각회향을 유효성분으로 포함하는 면역 증진용 조성물에 ...      1
2    본 출원은 신규한 터키 겨우살이의 추출물, 렉틴 및 상기 추출물 또는 렉틴의 제조방...      1
3    아로니아(Aronia) 열매 추출물, 댕댕이나무(Lonicera caerulea) ...      1
4    본 발명의 청각 추출물 및 홍삼 추출물을 포함하는 선천성 면역 증진용 조성물에 관한...      1
..                                                 ...    ...
145  본 발명은 엉겅퀴(Cirsium japonicum var. ussuriense) 잎...      1
146  본 발명은 어성초 초임계 추출물을 유효성분으로 함유하는 관절염 질환의 예방 및 치료...      1
147  본 발명은 항염증 활성과 파골세포 억제 효과를 갖는 두충 추출물, 상기 추출물을 유...      1
148  본 발명은 유효성분으로서 다음과 같은 진세노사이드 함량을 나타내는 홍삼 발효액을 포...      1
149  본 발명은 전통 한의약 이론에 근거하여 한방의 복합 생약추출물에 발효기술을 이용하여...      1

[150 rows x 2 columns]


In [ ]:
### DataFrame 자료형 생성 --> info() 함수 --> 전반적인 정보 제공

df.info() 

<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   sentence  147 non-null    object
 1   label     150 non-null    int64 
dtypes: int64(1), object(1)
memory usage: 3.5+ KB


In [ ]:
### 누락 데이터 확인 --> head() 함수 사용

print(df.head(15))

                                             sentence  label
0   본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...      1
1   본 발명은 타히보 추출물 및 팔각회향을 유효성분으로 포함하는 면역 증진용 조성물에 ...      1
2   본 출원은 신규한 터키 겨우살이의 추출물, 렉틴 및 상기 추출물 또는 렉틴의 제조방...      1
3   아로니아(Aronia) 열매 추출물, 댕댕이나무(Lonicera caerulea) ...      1
4   본 발명의 청각 추출물 및 홍삼 추출물을 포함하는 선천성 면역 증진용 조성물에 관한...      1
5   본 발명은 청각 추출물 및 홍삼 추출물을 포함하는 후천성 면역 증진용 조성물에 관한...      1
6   본 발명은 효소 처리된 노니 추출물을 유효 성분으로 포함하는 면역 증진 조성물 제조...      1
7   본 발명은 면역 억제 효과가 증진된 중간엽 줄기세포의 제조 방법 및 이로부터 제조된...      1
8   본 발명은 항산화 기능성 및 혈류개선에 효과가 있는 부추 유산균 발효액에 관한 것으...      1
9   본 발명은 좁은잎천선과 추출물을 유효성분으로 포함하는 면역 증진용 조성물에 관한 것이다.      1
10  본 발명은 동과씨 추출물을 유효성분으로 포함하는 면역 증진용 식품 조성물에 관한 것이다.      1
11  본 발명은 전처리한 우렁쉥이(Halocynthia roretzi) 껍질에 물 및 단...      1
12                                                NaN      1
13  본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...      1
14  본 발명은 비박피 양파를 숙성 및 발효하여 섭취자의 면역력을 증강시키면서도 양파 섭...      1


In [ ]:
### 특정 컬럼 추출 방법 --> 데이터프레임으로부터 특정 컬럼 인덱싱하기
print("첫번째")
print(df['sentence'])
print('-'*80)
print('두번째')
print(df.loc[:, 'sentence'])
print('-'*80)
print('세번째')
print(df.sentence)

첫번째
0      본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...
1      본 발명은 타히보 추출물 및 팔각회향을 유효성분으로 포함하는 면역 증진용 조성물에 ...
2      본 출원은 신규한 터키 겨우살이의 추출물, 렉틴 및 상기 추출물 또는 렉틴의 제조방...
3      아로니아(Aronia) 열매 추출물, 댕댕이나무(Lonicera caerulea) ...
4      본 발명의 청각 추출물 및 홍삼 추출물을 포함하는 선천성 면역 증진용 조성물에 관한...
                             ...                        
145    본 발명은 엉겅퀴(Cirsium japonicum var. ussuriense) 잎...
146    본 발명은 어성초 초임계 추출물을 유효성분으로 함유하는 관절염 질환의 예방 및 치료...
147    본 발명은 항염증 활성과 파골세포 억제 효과를 갖는 두충 추출물, 상기 추출물을 유...
148    본 발명은 유효성분으로서 다음과 같은 진세노사이드 함량을 나타내는 홍삼 발효액을 포...
149    본 발명은 전통 한의약 이론에 근거하여 한방의 복합 생약추출물에 발효기술을 이용하여...
Name: sentence, Length: 147, dtype: object
--------------------------------------------------------------------------------
두번째
0      본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...
1      본 발명은 타히보 추출물 및 팔각회향을 유효성분으로 포함하는 면역 증진용 조성물에 ...
2      본 출원은 신규한 터키 겨우살이의 추출물, 렉틴 및 상기 추출물 또는 렉틴의 제조방...
3      아로니아(Aronia) 열매 추출물, 댕댕이나무(Lonicera caerulea) ...
4      본 발명의 

In [ ]:
### 누락 데이터 확인 -->isnull() 사용
nulls = df.sentence.isnull().sum()
print(nulls)

print('-'*80)

# 전체 컬럼에 대해서 적용
nulls = df.isnull().sum()
print(nulls)

3
--------------------------------------------------------------------------------
sentence    3
label       0
dtype: int64


In [ ]:
### 누락 데이터의 자료형 확인

null = df.sentence[12]
print(null)

# 자료형 확인
print(f'누락 데이터의 자료형 = {type(null)}')

nan
누락 데이터의 자료형 = <class 'float'>


In [ ]:
### 누락 데이터 처리 --> 제거 --> 행 제거(1)

# 별도의 변수를 통해서 결과 저장 --> 제거
df_drop = df.dropna()
print(f'기존 데이터 프레임 : \n{df}')
print('-'*80)
print(f'누락 데이터가 제거된 새로운 데이터프레임 : \n{df_drop}')

기존 데이터 프레임 : 
                                              sentence  label
0    본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...      1
1    본 발명은 타히보 추출물 및 팔각회향을 유효성분으로 포함하는 면역 증진용 조성물에 ...      1
2    본 출원은 신규한 터키 겨우살이의 추출물, 렉틴 및 상기 추출물 또는 렉틴의 제조방...      1
3    아로니아(Aronia) 열매 추출물, 댕댕이나무(Lonicera caerulea) ...      1
4    본 발명의 청각 추출물 및 홍삼 추출물을 포함하는 선천성 면역 증진용 조성물에 관한...      1
..                                                 ...    ...
145  본 발명은 엉겅퀴(Cirsium japonicum var. ussuriense) 잎...      1
146  본 발명은 어성초 초임계 추출물을 유효성분으로 함유하는 관절염 질환의 예방 및 치료...      1
147  본 발명은 항염증 활성과 파골세포 억제 효과를 갖는 두충 추출물, 상기 추출물을 유...      1
148  본 발명은 유효성분으로서 다음과 같은 진세노사이드 함량을 나타내는 홍삼 발효액을 포...      1
149  본 발명은 전통 한의약 이론에 근거하여 한방의 복합 생약추출물에 발효기술을 이용하여...      1

[150 rows x 2 columns]
--------------------------------------------------------------------------------
누락 데이터가 제거된 새로운 데이터프레임 : 
                                              sentence  label
0    본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성

In [ ]:
### 누락된 행 제거 --> 확인 --> isnull().sum()
print(df_drop.isnull().sum())

sentence    0
label       0
dtype: int64


In [ ]:
### 누락 데이터 처리 --> 제거 --> 행 제거(2)

'''
dropna() 함수를 사용해서 원본 데이터 자체를 수정하고 싶은 경우,
==> df.dropna(inplace=True)
'''

df.dropna(inplace=True)

# 결과 확인하기
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 147 entries, 0 to 149
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   sentence  147 non-null    object
 1   label     147 non-null    int64 
dtypes: int64(1), object(1)
memory usage: 3.4+ KB


In [ ]:
### 누락된 데이터 처리(2) --> fillna() 함수 이용
df_new = df.fillna("내용 없음")

# 결과 확인하기
print("기존 데이터 프레임 : ")
df.info()
print('-'*80)
print('fillna 함수를 사용해서 누락 데이터를 처리 한 데이터 프레임 : ')
df_new.info()

기존 데이터 프레임 : 
<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   sentence  147 non-null    object
 1   label     150 non-null    int64 
dtypes: int64(1), object(1)
memory usage: 7.6+ KB
--------------------------------------------------------------------------------
fillna 함수를 사용해서 누락 데이터를 처리 한 데이터 프레임 : 
<class 'pandas.core.frame.DataFrame'>
Int64Index: 150 entries, 0 to 149
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   sentence  150 non-null    object
 1   label     150 non-null    int64 
dtypes: int64(1), object(1)
memory usage: 7.6+ KB


In [ ]:
### 내용 없음으로 채워졌는지 확인
print(df.sentence[12])
print('-'*80)
print(df_new.sentence[12])
print('-'*80)
print(df_new.iloc[11:13, :])

nan
--------------------------------------------------------------------------------
내용 없음
--------------------------------------------------------------------------------
                                             sentence  label
11  본 발명은 전처리한 우렁쉥이(Halocynthia roretzi) 껍질에 물 및 단...      1
12                                              내용 없음      1


In [ ]:
### value_counts() 함수 사용 --> 컬럼의 항목별 갯수 구하기

# 데이터 --> df
print(df.label)

print('-'*80)

# value_counts()
counts = df.label.value_counts()
print(f'label 컬럼의 항목별 갯수 : \n{counts}')

0      1
1      1
2      1
3      1
4      1
      ..
145    1
146    1
147    1
148    1
149    1
Name: label, Length: 150, dtype: int64
--------------------------------------------------------------------------------
label 컬럼의 항목별 갯수 : 
0    95
1    55
Name: label, dtype: int64


In [ ]:
### concat 데이터 생성

data1 = {'A' : ['A0', 'A1', 'A2', 'A3'],
         'B' : ['B0', 'B1', 'B2', 'B3'],
         'C' : ['C0', 'C1', 'C2', 'C3'],
         'D' : ['D0', 'D1', 'D2', 'D3']}

data2 = {'A' : ['A4', 'A5', 'A6', 'A7'],
         'B' : ['B4', 'B5', 'B6', 'B7'],
         'C' : ['C4', 'C5', 'C6', 'C7'],
         'D' : ['D4', 'D5', 'D6', 'D7']}

data3 = {'A' : ['A8', 'A9', 'A10', 'A11'],
         'B' : ['B8', 'B9', 'B10', 'B11'],
         'C' : ['C8', 'C9', 'C10', 'C11'],
         'D' : ['D8', 'D9', 'D10', 'D11']}

df1 = pd.DataFrame(data=data1, index=[0,1,2,3])
df2 = pd.DataFrame(data=data2, index=[4,5,6,7])
df3 = pd.DataFrame(data=data3, index=[8,9,10,11])

# 결과 확인하기
print(df1)
print('-'*80)
print(df2)
print('-'*80)
print(df3)

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
--------------------------------------------------------------------------------
    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7
--------------------------------------------------------------------------------
      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11


In [ ]:
### concat() 함수 --> axis=0 방향으로 병합하기

concat1 = pd.concat([df1,df2,df3], axis=0)

# 결과 확인하기
print(concat1)

print('-'*80)

# concat --> 매개변수 : axis --> 기본값 = 0
concat2 = pd.concat([df1,df2,df3])
# 결과 확인하기
print(concat2)

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11
--------------------------------------------------------------------------------
      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11


In [ ]:
### concat 함수 --> axis=1 방향으로 병합
concat3 = pd.concat([df1,df2,df3], axis=1)

# 결과 확인하기
print(concat3)

      A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A4   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A5   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A6   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A7   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11


## Numpy

In [ ]:
### 필요한 라이브러리 임폴트
import numpy as np

In [ ]:
### python list와 numpy nadrray 차이 --> 연산 가능 여부

# list 자료형 데이터 생성
list1 = [1,2,3]
list2 = [4,5,6]

# 리스트 자료형 --> 덧셈 연산 --> 불가능
result = list1 + list2
print(result)

print('-'*80)

# 리스트 자료형 --> 뺄셈 연산 --> 에러 발생
print(list1 - list2)

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.



[1, 2, 3, 4, 5, 6]
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-114-928189329b0b>", line 14, in <module>
    print(list1 - list2)
TypeError: unsupported operand type(s) for -: 'list' and 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/interactiveshell.py", line 2040, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'TypeError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/IPython/core/ultratb.py", line 1101, in get_records
    return _fixed_getinn

TypeError: ignored

In [ ]:
## np.array() + 리스트 자료형 --> numpy 1차원 배열(1-d array)
arr1 = np.array(list1)
arr2 = np.array(list2)

# 결과 확인하기
print(f'배열 1 : {arr1}')

print('-'*80)

print(f'배열 2 : {arr2}')

print('-'*80)

# 덧셈 연산
res1 = arr1 + arr2
print(res1)

print('-'*80)

# 뺄셈 연산
res2 = arr1 - arr2
print(res2)

배열 1 : [1 2 3]
--------------------------------------------------------------------------------
배열 2 : [4 5 6]
--------------------------------------------------------------------------------
[5 7 9]
--------------------------------------------------------------------------------
[-3 -3 -3]


In [ ]:
### np.arange() 함수 이용 --> 1차원 배열(array) 만들기

# 0부터 10미만까지 1만큼 간격으로 정수의 1차원 배열 만들기
arr1 = np.arange(0, 10, 1)
print(arr1)
arr2 = np.arange(10) # 같다
print(arr2)

print('-'*80)
print(f'자료형 확인 : {type(arr1)}')
print('-'*80)

# 1부터 15 미만까지 2만큼의 간격으로 연속적인 정수의 1차원 배열 만들기
arr3 = np.arange(1, 15, 2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------------------------------------
자료형 확인 : <class 'numpy.ndarray'>
--------------------------------------------------------------------------------
[ 1  3  5  7  9 11 13]


In [ ]:
### 연습 문제

'''
문제 : 1,2,3....50 정수의 배열이 담긴 1차원 배열을 생성
'''

# 풀이
arr = np.arange(1,51)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]


In [ ]:
### 2차원 배열(2-D array) 만들기

# 2차원 리스트 자료형 데이터 생성
mylist = [[1,2,3],[4,5,6],[7,8,9]]

# ndarray 생성 함수에 입력
arr = np.array(mylist)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
### 2차원 배열 만들기(2) --> np.arange().reshape(newshape=(m행,n열))

# np.arange() 사용 --> 1차원 배열 생성
arr1 = np.arange(12)
print(arr1)

print('-'*80)

# reshape() 사용 --> 1차원 배열을 (3, 4)의 2차원 배열로 변환
arr2 = arr1.reshape(3, 4)
print(arr2)

print('-'*80)

# 연속적인 콤보 적용
arr3 = np.arange(12).reshape(3, 4)
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
--------------------------------------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------------------------------------
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
### 배열의 모양 확인 --> 변수.shape

# 1차원 배열 생성하기 : [1,2,.....10] --> 원소 10개의 1차원 배열
arr1 = np.arange(1,11)
print(arr1)

print('-'*80)

# 1차원 배열의 모양 확인 --> .shape
shape1 = arr1.shape
print(f'1차원 배열의 모양 : {shape1}')

print('-'*80)

# 2차원 배열 생성하기 --> arr1 재활용
arr2 = arr1.reshape(2,5)
print(arr2)

print('-'*80)

# 2차원 배열의 모양 확인 --> .shape
print(f'2차원 배열의 모양 : {arr2.shape}')

[ 1  2  3  4  5  6  7  8  9 10]
--------------------------------------------------------------------------------
1차원 배열의 모양 : (10,)
--------------------------------------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
--------------------------------------------------------------------------------
2차원 배열의 모양 : (2, 5)


In [ ]:
### 보충 : pd.DataFrame() --> DataFrame 자료형 데이터 생성 --> df.shape

mydict = {'col1':[1,2],
          'col2':[3,4],
          'col3':[5,6]}

# 데이터프레임 자료형 데이터 생성
df = pd.DataFrame(data=mydict)
print(df)

print('-'*80)

# df.shape --> 모양 확인
print(f'생성된 데이터프레임의 모양 : {df.shape}')

   col1  col2  col3
0     1     3     5
1     2     4     6
--------------------------------------------------------------------------------
생성된 데이터프레임의 모양 : (2, 3)


In [ ]:
### 배열의 전체 원소 갯수 확인 --> 변수형.size

# 1차원 배열 생성
arr1 = np.arange(15)
print(arr1)

print('-'*80)

# 성분 원소의 갯수 확인(1)
print(f'배열의 성분 원소의 갯수 = {len(arr1)}')

print('-'*80)

# 성분 원소의 갯수 확인(2) --> size
print(f'배열의 성분 원소의 갯수 = {arr1.size}')

print('-'*80)

# 2차원 배열 생성
arr2 = np.arange(2,14).reshape(3,4)
print(arr2)

print('-'*80)

# 2차원 배열 --> 성분 원소의 갯수 확인 --> len() /.size
print(f'2차원 배열의 성분 원소의 갯수 = {len(arr2)}')
print('-'*80)
print(f'2차원 배열의 성분 원소의 갯수 = {arr2.size}')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
--------------------------------------------------------------------------------
배열의 성분 원소의 갯수 = 15
--------------------------------------------------------------------------------
배열의 성분 원소의 갯수 = 15
--------------------------------------------------------------------------------
[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
--------------------------------------------------------------------------------
2차원 배열의 성분 원소의 갯수 = 3
--------------------------------------------------------------------------------
2차원 배열의 성분 원소의 갯수 = 12


In [ ]:
### 연습문제 1  # 내 풀이
import pandas as pd

mylist = ['037730', '036360', '005670']
col = ['종목코드']
df = pd.DataFrame(data=mylist, columns=col)
print(df)

df['종목명'] = ['3R', '3SOFT', 'ACTS']
print(df)

df['현재가'] = [1510 , 1790, 1185]
print(df)

df['등락률'] = [7.36, 1.65, 1.28]
print(df)

     종목코드
0  037730
1  036360
2  005670
     종목코드    종목명
0  037730     3R
1  036360  3SOFT
2  005670   ACTS
     종목코드    종목명   현재가
0  037730     3R  1510
1  036360  3SOFT  1790
2  005670   ACTS  1185
     종목코드    종목명   현재가   등락률
0  037730     3R  1510  7.36
1  036360  3SOFT  1790  1.65
2  005670   ACTS  1185  1.28


In [ ]:
### 연습문제 1 # 강사 풀이

import pandas as pd

mylist = [['037730', '3R', 1510, 7.36],
          ['036360', '3SOFT', 1790, 1.65],
          ['005670', 'ACTS', 1185, 1.28]
          ]

mycolumns = ['종목코드', '종목명', '현재가', '등락률']
df = pd.DataFrame(data=mylist, columns=mycolumns)
print(df)

     종목코드    종목명   현재가   등락률
0  037730     3R  1510  7.36
1  036360  3SOFT  1790  1.65
2  005670   ACTS  1185  1.28


In [ ]:
### 연습문제 2

fancy = df[['현재가', '등락률']]
print(fancy)

    현재가   등락률
0  1510  7.36
1  1790  1.65
2  1185  1.28


In [ ]:
### 연습문제 3

mylist = [['3R', 1510, 7.36],
          ['3SOFT', 1790, 1.65],
          ['ACTS', 1185, 1.28]]

myindex = ['037730', '036360', '005670']

mycolumns = ['종목명', '현재가', '등락률']

df = pd.DataFrame(data=mylist, index=myindex, columns=mycolumns)

print(df)

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  1.65
005670   ACTS  1185  1.28


In [ ]:
### 연습문제 4

# 4-1 --> loc 인덱서 사용
sliced1 = df.loc['037730':'036360', :]
print(sliced1)

print('-'*80)

# 4-1 --> iloc 인덱서 사용
sliced2 = df.iloc[:2, :]
print(sliced2)

print('-'*80)

# 4-1 --> fancy 인덱싱 응용
sliced3 = df.loc[['037730', '036360'], :]
print(sliced3)

print('-'*80)

# 4-2 --> loc 인덱서 사용
res = df.loc['037730', '현재가']
print(res)

print('-'*80)

# 4-2 --> iloc 인덱서 사용
res = df.iloc[0, 1]
print(res)

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  1.65
--------------------------------------------------------------------------------
          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  1.65
--------------------------------------------------------------------------------
          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  1.65
--------------------------------------------------------------------------------
1510
--------------------------------------------------------------------------------
1510


In [ ]:
### 연습문제 5

condition = df['현재가'] >= 1400

print(df.loc[condition, :])

          종목명   현재가   등락률
037730     3R  1510  7.36
036360  3SOFT  1790  1.65


In [ ]:
### 연습문제 6

condition = (df['현재가'] >= 1400) & (df['현재가'] < 1700)

print(df.loc[condition, :])

       종목명   현재가   등락률
037730  3R  1510  7.36


In [12]:
### 배열의 차원 확인

import numpy as np

# 1차원 배열 생성
arr1 = np.arange(1,31,1)
print(arr1)

print('-'*80)

# 2차원 배열 생성 --> 1차원 배열 재구성
arr2 = arr1.reshape((3,10))
print(arr2)

print('-'*80)

# 1차원 배열의 모양과 차원 확인
print(f'1차원 배열의 모양 = {arr1.shape}')
print(f'1차원 배열의 차원 = {arr1.ndim}')

print('-'*80)

# 2차원 배열의 모양과 차원 확인
print(f'2차원 배열의 모양 = {arr2.shape}')
print(f'2차원 배열의 확인 = {arr2.ndim}')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]
--------------------------------------------------------------------------------
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27 28 29 30]]
--------------------------------------------------------------------------------
1차원 배열의 모양 = (30,)
1차원 배열의 차원 = 1
--------------------------------------------------------------------------------
2차원 배열의 모양 = (3, 10)
2차원 배열의 확인 = 2


In [17]:
### 3차원 배열 생성 --> np.arange().reshape((행, 열, 깊이))

# 1차원 배열 생성
arr1 = np.arange(0,24,1)
print(arr1)

print('-'*80)

# reshape() 함수를 이용 --> (4, 3, 2)
arr2 = arr1.reshape((4, 3, 2))
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
--------------------------------------------------------------------------------
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [27]:
### 연습문제

# 목표 : (2,2,2) 모양의 3차원 배열 생성

# 1차원 배열 생성
arr1 = np.arange(1,9)
print(arr1)

print('-'*80)

# 3차원 배열 생성
arr2 = arr1.reshape((2,2,2))
print(arr2)

print('-'*80)

# 모양 확인하는 코드
shape = arr2.shape
print(f'생성된 배열의 모양 = {shape}')

print('-'*80)

# 차원 확인하는 코드
n_dim = arr2.ndim
print(f'생성된 배열의 차원 = {n_dim}')

print('-'*80)

# 성분 원소의 갯수 확인하는 코드
n_size = arr2.size
print(f'생성된 배열의 원소의 수 = {n_size}')

[1 2 3 4 5 6 7 8]
--------------------------------------------------------------------------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
--------------------------------------------------------------------------------
생성된 배열의 모양 = (2, 2, 2)
--------------------------------------------------------------------------------
생성된 배열의 차원 = 3
--------------------------------------------------------------------------------
생성된 배열의 원소의 수 = 8


In [33]:
### 인덱싱 --> 특정 원소 접근

# 2차원 배열 생성하기
arr = np.arange(1,7).reshape((2,3))
print(arr)

print('-'*80)

# 행 인덱싱 --> 0번째 행 인덱싱 --> 0번째 행에 속하는 열은 모두 포함
row1 = arr[0]
print(f'행 인덱싱의 결과 = {row1}')

print('-'*80)

# 행렬 인덱싱 --> 0번째 행, 0번째 열 인덱싱
row_col1 = arr[0][0]
row_col2 = arr[0,0]
print(f'행렬 인덱싱의 결과(1) : {row_col1}')
print(f'행렬 인덱싱의 결과(2) : {row_col2}')

[[1 2 3]
 [4 5 6]]
--------------------------------------------------------------------------------
행 인덱싱의 결과 = [1 2 3]
--------------------------------------------------------------------------------
행렬 인덱싱의 결과(1) : 1
행렬 인덱싱의 결과(2) : 1


In [40]:
### 3차원 배열에 대한 인덱싱

# 3차원 배열 생성 --> 모양(2,3,2)
arr = np.arange(12).reshape((2,3,2))
print(arr)

print('-'*80)

# 행 인덱싱 --> 1번행 인덱싱
row1 = arr[1]
row2 = arr[1, :]
print(f'1번행 인덱싱의 결과 : \n{row1}')
print(f'1번행 인덱싱의 결과 : \n{row2}')

print('-'*80)

# 행렬 인덱싱 --> 1번행 1번열 인덱싱
row_col1 = arr[1][1]
row_col2 = arr[1,1]
print(f'1번행 1번열 인덱싱의 결과 : {row_col1}')
print(f'1번행 1번열 인덱싱의 결과 : {row_col2}')

print('-'*80)

# 행렬깊이 인덱싱 --> 1번행, 1번열, 1번 깊이 인덱싱
row_col_depth1 = arr[1][1][1]
row_col_depth2 = arr[1,1,1]
print(f'1번행 1번열 1번 깊이 인덱싱의 결과 = {row_col_depth1}')
print(f'1번행 1번열 1번 깊이 인덱싱의 결과 = {row_col_depth2}')

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
--------------------------------------------------------------------------------
1번행 인덱싱의 결과 : 
[[ 6  7]
 [ 8  9]
 [10 11]]
1번행 인덱싱의 결과 : 
[[ 6  7]
 [ 8  9]
 [10 11]]
--------------------------------------------------------------------------------
1번행 1번열 인덱싱의 결과 : [8 9]
1번행 1번열 인덱싱의 결과 : [8 9]
--------------------------------------------------------------------------------
1번행 1번열 1번 깊이 인덱싱의 결과 = 9
1번행 1번열 1번 깊이 인덱싱의 결과 = 9


In [43]:
### 1차원 배열 슬라이싱

# np.arange() --> 0부터 9까지 10개의 정수로 구성된 1차원 배열 생성
arr = np.arange(10)
print(arr)

print('-'*80)

# 4번째 ~ 8번째 원소까지 가져오기
sliced = arr[3:8]
print(sliced)

[0 1 2 3 4 5 6 7 8 9]
--------------------------------------------------------------------------------
[3 4 5 6 7]


In [46]:
### 2차원 배열 슬라이싱

# 0부터 49까지 연속적인 정수의 1차원 배열 생성
arr1 = np.arange(50)
print(arr1)

print('-'*80)

# (5, 10) 모양의 2차원 배열 생성
arr2 = arr1.reshape((5,10))
print(arr2)

print('-'*80)

# 행 : 첫번째 두번째까지, 열 : 모든 열
sliced1 = arr2[0:2, :]
print(sliced1)

print('-'*80)

# 행 : 모든 행, 열 : 0번 열
sliced2 = arr2[:, 0]
print(sliced2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
--------------------------------------------------------------------------------
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
--------------------------------------------------------------------------------
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
--------------------------------------------------------------------------------
[ 0 10 20 30 40]
