In [7]:
'''
# 문제1

아래의 혈액형 통계 수치를 이용하여 혈액형을 인덱스로 하는 pandas.Series 자료형을 생성하시오.
단, 단위(%)는 포함하지 않습니다.

A  : 34.2 %
B  : 27.1 %
O  : 26.7 %
AB : 11.5 %

'''

### 정답

import pandas as pd

data = [34.2, 27.1, 26.7, 11.5]
ind = ['A', 'B', 'O', 'AB']

df = pd.Series(data=data, index=ind)
print(df)

A     34.2
B     27.1
O     26.7
AB    11.5
dtype: float64


In [51]:
'''
# 문제2

아래의 단계별로 코드를 작성하시오.

# 1단계
각자의 구글 드라이브, 정형데이터분석시각화 폴더에 있는 dataframe.csv 파일을 read_csv() 함수를 이용하여 데이터프레임 자료형을 생성하시오.
단, 한글로 된 문장이 깨지지 않게 매개 변수를 설정하고, 'unnamed:0' 컬럼이 출력되지 않도록 코드를 작성하시오 

# 2단계
상위 15개의 행을 출력하시오.

# 3단계
sentence 컬럼에 존재하는 결측치(missing value)의 수를 출력하시오

# 4단계
dropna() 함수를 사용하여 데이터프레임 전체에 대해서 결측치를 제거하고, df_new라는 이름으로 결과를 저장하시오.

# 5단계
label 컬럼의 항목별 갯수를 구하시오.

'''

### 정답

# 1단계
from google.colab import drive
drive.mount('/content/drive')

file_path = '/content/drive/MyDrive/KDT/정형데이터분석시각화/dataframe.csv'

df = pd.read_csv(file_path, encoding='cp949', index_col=0)
print(df)

print('-'*80)

# 2단계
print(df[0:15])

print('-'*80)

print(df.head(15))

print('-'*80)

# 3단계
print(df['sentence'].isnull().sum())

print('-'*80)

print(df.sentence.isnull().sum())

print('-'*80)

# 4단계
df_new = df.dropna()
print(df_new)

print('-'*80)

# 5단계
counts = df.label.value_counts()
print(f'label 컬럼의 항목별 갯수 : \n{counts}')


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
                                              sentence  label
0    본 발명은 2종 이상의 생약 추출물을 유효성분으로 포함하는, 면역력 증진용 조성물 ...      1
1    본 발명은 타히보 추출물 및 팔각회향을 유효성분으로 포함하는 면역 증진용 조성물에 ...      1
2    본 출원은 신규한 터키 겨우살이의 추출물, 렉틴 및 상기 추출물 또는 렉틴의 제조방...      1
3    아로니아(Aronia) 열매 추출물, 댕댕이나무(Lonicera caerulea) ...      1
4    본 발명의 청각 추출물 및 홍삼 추출물을 포함하는 선천성 면역 증진용 조성물에 관한...      1
..                                                 ...    ...
145  본 발명은 엉겅퀴(Cirsium japonicum var. ussuriense) 잎...      1
146  본 발명은 어성초 초임계 추출물을 유효성분으로 함유하는 관절염 질환의 예방 및 치료...      1
147  본 발명은 항염증 활성과 파골세포 억제 효과를 갖는 두충 추출물, 상기 추출물을 유...      1
148  본 발명은 유효성분으로서 다음과 같은 진세노사이드 함량을 나타내는 홍삼 발효액을 포...      1
149  본 발명은 전통 한의약 이론에 근거하여 한방의 복합 생약추출물에 발효기술을 이용하여...      1

[150 rows x 2 columns]
--------------------------------------------------------------------------------
                      

In [54]:
'''
# 문제3

np.arange() 함수를 사용하여 아래와 같이 출력이 될 수 있는 1차원 넘파이 배열을 생성하시오

[ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

'''

### 정답
import numpy as np

num = np.arange(0,30,2)
print(num)
print(type(num))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
<class 'numpy.ndarray'>


In [58]:
'''
# 문제4

아래의 단계별로 코드를 작성하시오.

# 1단계
np.arange() 함수를 사용하여 1 ~ 25 사이의 연속된 숫자(25개)를 가지는 넘파이 1차원 배열을 생성하시오.

# 2단계
1차원 넘파이 배열을 (5, 5)의 모양을 가지는 넘파이 2차원 배열을 생성하시오.

# 3단계
2단계에서 생성한 넘파이 2차원 배열을 이용해서 dataframe을 생성하시오.
단, 컬럼의 이름은 'a', 'b', 'c', 'd', 'e'로 설정하시오

'''

### 정답

# 1단계
arr = np.arange(1,26)
print(arr)

print('-'*80)

# 2단계
arr2 = arr.reshape((5,5))
print(arr2)
print(arr2.shape)

print('-'*80)

# 3딘계
df = pd.DataFrame(arr2, columns=['a','b','c','d','e'])
print(df)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
--------------------------------------------------------------------------------
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)
--------------------------------------------------------------------------------
    0   1   2   3   4
a   1   2   3   4   5
b   6   7   8   9  10
c  11  12  13  14  15
d  16  17  18  19  20
e  21  22  23  24  25


In [37]:
'''
# 문제5

아래의 단계별로 코드를 작성하시오.

# 1단계
넘파이 배열에 관한 함수를 사용하여 다음과 같은 값을 갖는 넘파이 2차원 배열을 생성하시오.

[[ 1, 2, 3, 4],
 [ 5, 6, 7, 8],
 [ 9, 10, 11, 12]]


# 2단계
아래와 같은 값이 나오도록 슬라이싱하시오.

[[ 2,  3],
 [ 6,  7],
 [10, 11]]

'''

### 정답

# 1단계
num = np.arange(1,13).reshape(3,4)
print(num)

print('-'*80)

# 2단계
print(num[:,1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--------------------------------------------------------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]]
